spring:
  jpa:
    open-in-view: false
    show-sql: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.orm.jdbc.bind: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
