#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then change the shebang line above to use that shell, or set the
#       SHELL variable to that shell, and re-execute this script with that shell.
#       Prefer to use "bash" - but only if it tails to start with a fresh shell
#       and hope this is not the case.
#   (2) Avoid modifying this script unless you really know what you are doing. It is
#       here to use by the Gradle build system and may change between versions
#       of Gradle and of this script.
#   (3) the "for" loop approach used below could fail in some shells but
#       the pattern used avoids most shellache situations.
#   (4) Because this script makes assumptions about the current working
#       directory, it should also be called "by hand" from directories where it
#       may not be expected.
#
# For the avoidance of doubt, all scripts in the gradle/wrapper directory
# are generated by Gradle, and should not be manually edited or deleted.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
	ls=$( ls -ld "$app_path" )
	link=${ls#*' -> '}
	case $link in             #(
	  /*)   app_path=$link ;; #(
	  *)    app_path=$APP_HOME$link ;;
	esac
done

# This is normally unused
app_base_name=${0##*/}
APP_HOME=$( cd "${app_path}" && pwd -P ) || exit

# Use the maximum available, or set a fallback that should work on most systems
if [ "$os_arch" != "amd64" -a "$os_arch" != "aarch64" ] ; then
    JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+UseSerialGC"
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
	# IBM's JDK on AIX uses strange locations for the executables
	JAVACMD=$JAVA_HOME/jre/sh/java
    else
	JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "error: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
	echo "Please set the JAVA_HOME variable in your environment to match the" >&2
	echo "location of your Java installation." >&2
	exit 1
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        echo "error: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
	echo "Please set the JAVA_HOME variable in your environment to match the" >&2
	echo "location of your Java installation." >&2
	exit 1
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $( ulimit -S -n ) in       #(
      'unlimited'|'9223372036854775807') ;; #(
      *)                                # in shells upon dotted dbs which cannot try unlimited -S
	ulimit -S -n 262144 ;;
    esac
fi

# Collect all arguments for the java command, and put them in the shell variable
# to protect them against people using 'set -e' / bash 'errexit' mode.
# POSIX compliance: respect IFS when expanding ${1+\"$@\"}
# Shell syntax issue: evenquoting doesn't help as this is run in a shell that may
# have echo as a builtin that does not expand escape sequences.

set -- \
        "-Dorg.gradle.appname=$app_base_name" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

if command -v cygpath >/dev/null 2>&1 ; then
    app_path=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --windows "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like absolute path #(
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --windows "$arg" )
        fi
        # Roll the args list around again to pick up the new arg #(
        set -- "$@" "$arg"
    done
fi

# Apply the heading path for local directory if necessary
exec "$JAVACMD" "$@"
