#!/bin/bash
# Setup script to configure test environment variables
# Prompts for passwords or uses environment variables
# Generates SSL keystores if they don't exist

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE_ROOT="$SCRIPT_DIR/.env"
ENV_FILE_E2E="$SCRIPT_DIR/app/src/testE2E/resources/.env"
KEYSTORE_E2E="$SCRIPT_DIR/app/src/testE2E/resources/ssl/keystore.p12"
KEYSTORE_SYSTEM="$SCRIPT_DIR/app/src/testSystem/resources/ssl/keystore.p12"
KEYSTORE_MAIN="$SCRIPT_DIR/app/src/main/resources/keystore.p12"
KEYSTORE_TEST="$SCRIPT_DIR/app/src/test/resources/ssl/keystore.p12"
SSL_PASSWORD_FROM_ENV=false
POSTGRES_PASSWORD_FROM_ENV=false
H2_PASSWORD_FROM_ENV=false

if [ -f "$ENV_FILE_ROOT" ] || [ -f "$ENV_FILE_E2E" ]; then
    echo "⚠️  Existing .env file detected"
    [ -f "$ENV_FILE_ROOT" ] && echo "   - $ENV_FILE_ROOT"
    [ -f "$ENV_FILE_E2E" ] && echo "   - $ENV_FILE_E2E"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted. Using existing .env file."
        exit 0
    fi
fi

echo "Setting up test environment variables"
echo "Press Enter to use the suggested value or type your own"
echo ""

# SSL_KEYSTORE_PASSWORD - special handling for keystore generation
if [ -n "$SSL_KEYSTORE_PASSWORD" ]; then
    echo "Using SSL_KEYSTORE_PASSWORD from environment variable"
    echo "Note: This password will NOT be written to .env since it's already in your environment"
    SSL_PASSWORD_FROM_ENV=true
else
    read -sp "SSL_KEYSTORE_PASSWORD [generate random]: " ssl_password
    echo
    if [ -z "$ssl_password" ]; then
        # Generate a random password if none provided
        SSL_KEYSTORE_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')
        echo "Generated random SSL_KEYSTORE_PASSWORD"
    else
        SSL_KEYSTORE_PASSWORD=$ssl_password
    fi
fi

# H2_USERNAME
if [ -z "$H2_USERNAME" ]; then
    read -p "H2_USERNAME [sa]: " h2_username
    H2_USERNAME=${h2_username:-sa}
fi

# H2_PASSWORD
if [ -n "$H2_PASSWORD" ]; then
    echo "Using H2_PASSWORD from environment variable"
    echo "Note: This password will NOT be written to .env files"
    H2_PASSWORD_FROM_ENV=true
else
    read -sp "H2_PASSWORD [generate strong password]: " h2_password
    echo
    if [ -z "$h2_password" ]; then
        # Generate a random password if none provided
        H2_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')
        echo "Generated random H2_PASSWORD"
    else
        H2_PASSWORD=$h2_password
    fi
fi

# POSTGRES_DB
if [ -z "$POSTGRES_DB" ]; then
    read -p "POSTGRES_DB [familyties]: " postgres_db
    POSTGRES_DB=${postgres_db:-familyties}
fi

# POSTGRES_USER
if [ -z "$POSTGRES_USER" ]; then
    read -p "POSTGRES_USER [familyties]: " postgres_user
    POSTGRES_USER=${postgres_user:-familyties}
fi

# POSTGRES_PASSWORD
if [ -n "$POSTGRES_PASSWORD" ]; then
    echo "Using POSTGRES_PASSWORD from environment variable"
    echo "Note: This password will NOT be written to .env files"
    POSTGRES_PASSWORD_FROM_ENV=true
else
    read -sp "POSTGRES_PASSWORD [generate random, environment-only]: " postgres_password
    echo
    if [ -z "$postgres_password" ]; then
        # Generate a random password if none provided
        POSTGRES_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')
        echo "Generated random POSTGRES_PASSWORD"
    else
        POSTGRES_PASSWORD=$postgres_password
    fi
fi

# SERVER_PORT
if [ -z "$SERVER_PORT" ]; then
    read -p "SERVER_PORT [8443]: " server_port
    SERVER_PORT=${server_port:-8443}
fi

# Generate keystores if they don't exist
echo ""
echo "Checking SSL keystores..."

generate_keystore() {
    local keystore_path=$1
    local keystore_dir=$(dirname "$keystore_path")
    
    # Create directory if it doesn't exist
    mkdir -p "$keystore_dir"
    
    if [ ! -f "$keystore_path" ]; then
        echo "Generating keystore: $keystore_path"
        keytool -genkeypair -alias familyties -keyalg RSA -keysize 2048 \
            -storetype PKCS12 -keystore "$keystore_path" \
            -storepass "$SSL_KEYSTORE_PASSWORD" -keypass "$SSL_KEYSTORE_PASSWORD" \
            -validity 3650 \
            -dname "CN=localhost, OU=Test, O=FamilyTies, L=City, ST=State, C=US" \
            2>/dev/null
        echo "✅ Generated $keystore_path"
    else
        echo "✅ Keystore already exists: $keystore_path"
    fi
}

generate_keystore "$KEYSTORE_E2E"
generate_keystore "$KEYSTORE_SYSTEM"
generate_keystore "$KEYSTORE_MAIN"
generate_keystore "$KEYSTORE_TEST"

# Create .env file
cat > "$ENV_FILE_ROOT" <<EOF
# Environment variables for testing
# Generated by setup-test-env.sh on $(date +"%Y-%m-%d %H:%M:%S")
# This file is gitignored and will NOT be committed

# SSL_KEYSTORE_PASSWORD is environment-only and MUST be set in your shell.
# It is intentionally not written to .env files.
# POSTGRES_PASSWORD is environment-only and MUST be set in your shell.
# It is intentionally not written to .env files.
# H2_PASSWORD is environment-only and MUST be set in your shell.
# It is intentionally not written to .env files.
EOF

cat >> "$ENV_FILE_ROOT" <<EOF

# H2 Database Configuration (for unit and component tests)
H2_USERNAME=$H2_USERNAME

# PostgreSQL Configuration (for E2E tests with Docker Compose)
POSTGRES_DB=$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER

# Server Configuration
SERVER_PORT=$SERVER_PORT
EOF

# Keep root and E2E .env files synchronized for deterministic test/compose behavior
mkdir -p "$(dirname "$ENV_FILE_E2E")"
cp "$ENV_FILE_ROOT" "$ENV_FILE_E2E"

echo ""
echo "✅ Created synchronized .env files:"
echo "   - $ENV_FILE_ROOT"
echo "   - $ENV_FILE_E2E"
echo ""
echo "Environment variables configured:"
echo "  SSL_KEYSTORE_PASSWORD=****"
echo "  H2_USERNAME=$H2_USERNAME"
echo "  H2_PASSWORD=****"
echo "  POSTGRES_DB=$POSTGRES_DB"
echo "  POSTGRES_USER=$POSTGRES_USER"
echo "  POSTGRES_PASSWORD=****"
echo "  SERVER_PORT=$SERVER_PORT"
echo ""
echo "You can now run tests with:"
echo "  ./gradlew test"
echo "  ./gradlew testE2E"
echo ""
if [ "$SSL_PASSWORD_FROM_ENV" = false ] || [ "$POSTGRES_PASSWORD_FROM_ENV" = false ] || [ "$H2_PASSWORD_FROM_ENV" = false ]; then
    echo "⚠️  Some secrets were generated/input but not persisted."
    echo "    Export them in your shell before running tests, for example:"
    if [ "$SSL_PASSWORD_FROM_ENV" = false ]; then
        echo "    export SSL_KEYSTORE_PASSWORD='$SSL_KEYSTORE_PASSWORD'"
    fi
    if [ "$POSTGRES_PASSWORD_FROM_ENV" = false ]; then
        echo "    export POSTGRES_PASSWORD='$POSTGRES_PASSWORD'"
    fi
    if [ "$H2_PASSWORD_FROM_ENV" = false ]; then
        echo "    export H2_PASSWORD='$H2_PASSWORD'"
    fi
fi
echo "⚠️  The .env files and keystore.p12 files are gitignored and will NOT be committed."

echo ""
echo "=== Activating Git hooks ==="
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
git -C "$REPO_ROOT" config core.hooksPath .githooks
chmod +x "$REPO_ROOT/.githooks/pre-commit" "$REPO_ROOT/.githooks/pre-push"
echo "✅ Git hooks activated (pre-commit, pre-push)"
echo "   Keystores, secrets, and workflow files are now protected."
