#!/bin/bash
# Setup script to configure test environment variables for vanilla-ms
# No SSL or keystore generation — vanilla-ms runs plain HTTP.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE_ROOT="$SCRIPT_DIR/.env"
ENV_FILE_E2E="$SCRIPT_DIR/app/src/testE2E/resources/.env"

if [ -f "$ENV_FILE_ROOT" ] || [ -f "$ENV_FILE_E2E" ]; then
    echo "⚠️  Existing .env file detected"
    [ -f "$ENV_FILE_ROOT" ] && echo "   - $ENV_FILE_ROOT"
    [ -f "$ENV_FILE_E2E" ] && echo "   - $ENV_FILE_E2E"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted. Using existing .env file."
        exit 0
    fi
fi

echo "Setting up test environment variables for vanilla-ms"
echo "Press Enter to use the suggested value or type your own"
echo ""

# H2_USERNAME
if [ -z "$H2_USERNAME" ]; then
    read -p "H2_USERNAME [sa]: " h2_username
    H2_USERNAME=${h2_username:-sa}
fi

# H2_PASSWORD
POSTGRES_PASSWORD_FROM_ENV=false
H2_PASSWORD_FROM_ENV=false
if [ -n "$H2_PASSWORD" ]; then
    echo "Using H2_PASSWORD from environment variable"
    H2_PASSWORD_FROM_ENV=true
else
    read -sp "H2_PASSWORD [generate random]: " h2_password
    echo
    if [ -z "$h2_password" ]; then
        H2_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')
        echo "Generated random H2_PASSWORD"
    else
        H2_PASSWORD=$h2_password
    fi
fi

# POSTGRES_DB
if [ -z "$POSTGRES_DB" ]; then
    read -p "POSTGRES_DB [familyties]: " postgres_db
    POSTGRES_DB=${postgres_db:-familyties}
fi

# POSTGRES_USER
if [ -z "$POSTGRES_USER" ]; then
    read -p "POSTGRES_USER [familyties]: " postgres_user
    POSTGRES_USER=${postgres_user:-familyties}
fi

# POSTGRES_PASSWORD
if [ -n "$POSTGRES_PASSWORD" ]; then
    echo "Using POSTGRES_PASSWORD from environment variable"
    POSTGRES_PASSWORD_FROM_ENV=true
else
    read -sp "POSTGRES_PASSWORD [generate random]: " postgres_password
    echo
    if [ -z "$postgres_password" ]; then
        POSTGRES_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')
        echo "Generated random POSTGRES_PASSWORD"
    else
        POSTGRES_PASSWORD=$postgres_password
    fi
fi

# Write .env files
cat > "$ENV_FILE_ROOT" <<EOF
# Environment variables for vanilla-ms testing
# Generated by setup-test-env.sh on $(date +"%Y-%m-%d %H:%M:%S")
# This file is gitignored and will NOT be committed

# H2_PASSWORD is environment-only and MUST be set in your shell.
# POSTGRES_PASSWORD is environment-only and MUST be set in your shell.

# H2 Database Configuration (for unit and component tests)
H2_USERNAME=$H2_USERNAME

# PostgreSQL Configuration (for E2E tests with Docker Compose)
POSTGRES_DB=$POSTGRES_DB
POSTGRES_USER=$POSTGRES_USER
EOF

mkdir -p "$(dirname "$ENV_FILE_E2E")"
cp "$ENV_FILE_ROOT" "$ENV_FILE_E2E"

echo ""
echo "✅ Created synchronized .env files:"
echo "   - $ENV_FILE_ROOT"
echo "   - $ENV_FILE_E2E"
echo ""
echo "Environment variables configured:"
echo "  H2_USERNAME=$H2_USERNAME"
echo "  H2_PASSWORD=****"
echo "  POSTGRES_DB=$POSTGRES_DB"
echo "  POSTGRES_USER=$POSTGRES_USER"
echo "  POSTGRES_PASSWORD=****"
echo ""
if [ "$H2_PASSWORD_FROM_ENV" = false ] || [ "$POSTGRES_PASSWORD_FROM_ENV" = false ]; then
    echo "⚠️  Secrets were generated/input but not persisted."
    echo "    Export them in your shell before running tests:"
    if [ "$H2_PASSWORD_FROM_ENV" = false ]; then
        echo "    export H2_PASSWORD='$H2_PASSWORD'"
    fi
    if [ "$POSTGRES_PASSWORD_FROM_ENV" = false ]; then
        echo "    export POSTGRES_PASSWORD='$POSTGRES_PASSWORD'"
    fi
fi
echo ""
echo "You can now run tests with:"
echo "  ./gradlew test"
echo "  ./gradlew testE2E"
