spring:
  datasource:
    url: jdbc:tc:postgresql:17.4-alpine:///familyties?TC_DAEMON=true
    username: familyties
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.testcontainers: INFO

server:
  port: 8081
